### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by lesderid** [MidasLamb/Pomodoro#2]
The project contains no license. This makes it proprietary software by default (i.e. not open-source).

In [package.json](https://github.com/MidasLamb/Pomodoro/blob/6212dde1ee0c86e1b24c5ba45e3082ec9c8bc198/package.json#L21), the ISC license is specified. The ISC license requires you to provide a copy of the full license along with the project for it to apply.

**Comment by MidasLamb** [comment]
Thanks for pointing this out
